// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfKtT8APM1I6kcQvQy34DzbhHNTseMr5w',
    appId: '1:154238924613:web:d1c66398462fba3f1c302c',
    messagingSenderId: '154238924613',
    projectId: 'geo-farm-bogobogo-sort',
    authDomain: 'geo-farm-bogobogo-sort.firebaseapp.com',
    storageBucket: 'geo-farm-bogobogo-sort.appspot.com',
    measurementId: 'G-4ZRGQT7PBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAO0SdwIIzZ5T6Obj5xK_GKeYPxvKRsFM',
    appId: '1:154238924613:android:944fe1c1fb9632531c302c',
    messagingSenderId: '154238924613',
    projectId: 'geo-farm-bogobogo-sort',
    storageBucket: 'geo-farm-bogobogo-sort.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsWeVOkk_xIpo3FwRrgnEuh4OUz-76Thw',
    appId: '1:154238924613:ios:86fccdcc941076c61c302c',
    messagingSenderId: '154238924613',
    projectId: 'geo-farm-bogobogo-sort',
    storageBucket: 'geo-farm-bogobogo-sort.appspot.com',
    iosBundleId: 'com.example.geoFarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsWeVOkk_xIpo3FwRrgnEuh4OUz-76Thw',
    appId: '1:154238924613:ios:36fc47f1c3883a671c302c',
    messagingSenderId: '154238924613',
    projectId: 'geo-farm-bogobogo-sort',
    storageBucket: 'geo-farm-bogobogo-sort.appspot.com',
    iosBundleId: 'com.example.geoFarm.RunnerTests',
  );
}
